PREFIX dc: <http://purl.org/dc/elements/1.1/>
prefix schema: <https://schema.org/>

select ?title ?instructor ?artwork
where {
    ?track a dc:Event ;
  		dc:title ?title .
  
  	optional {
  		?track schema:performer ?instructor .
    }
  
  	optional {
    	?track schema:workPresented ?presentation .
    }
 
    optional {
        ?presentation schema:mentions ?artwork .
    }
}
